/*
choix du mot ok
coder le mot ok
saisi lettre gestion clavier et souris
tester lettre ok
afficher lettres ok
tester gagner
gagner
perdu
rejouer
*/
var dico = [
    'BOUBOULE',
    'ANNA',
    'JAVASCRIPT',
    'VOITURE',
    'SORCIERE-DU-VENT',
    'AEROPORT',
    'AFFAIRE',
    'ALBUM',
    'ALPHABET',
    'AMENER',
    'AMPOULE',
    'ANCIEN',
    'ANORAK',
    'ANTENNE',
    'APPAREIL',
    'APPORTER',
    'APPUYER',
    'APRES',
    'ARC',
    'ARMOIRE',
    'ARRET',
    'ARRIERE',
    'ARRIVER',
    'ARROSER',
    'ASSIETTE',
    'ASSIS',
    'ATTACHER',
    'ATTENDRE',
    'ATTENTION',
    'ATTERRIR',
    'ATTRAPER',
    'AU',
    'AUTANT',
    'AUTO',
    'AUTOMOBILISTE',
    'AUTORADIO',
    'AUTOUR',
    'AVANCER',
    'AVANT',
    'AVEC',
    'AVION',
    'BAGAGE',
    'BAGUETTE',
    'BAIGNER',
    'BÂILLER',
    'BALLE',
    'BANC',
    'BARBE',
    'BARBOTER',
    'BARQUE',
    'BARRE',
    'BARREAU',
    'BAS',
    'BATEAU',
    'BEAUCOUP',
    'BIBLIOTHEQUE',
    'BLANC',
    'BLEU',
    'BOIS',
    'BOITE',
    'BONDIR',
    'BONNET',
    'BORD',
    'BOSSER',
    'BOTTE',
    'BOUCHER',
    'BOUCHON',
    'BOUDER',
    'BOUGER',
    'BOUSCULER',
    'BOUT',
    'BOUTEILLE',
    'BOUTON',
    'BRAS',
    'BRETELLE',
    'BRICOLAGE',
    'BRUIT',
    'BRUN',
    'BULLES',
    'BUREAU',
    'CABANE',
    'CABINET',
    'CAGOULE',
    'CAHIER',
    'CAISSE',
    'CALME',
    'CAMARADE',
    'CAMESCOPE',
    'CAMION',
    'CANARD',
    'CARNET',
    'CARREAU',
    'CARTABLE',
    'CARTON',
    'CASIER',
    'CASQUE',
    'CASQUETTE',
    'CASSE',
    'CASSER',
    'CASSEROLE',
    'CASSETTE',
    'CATALOGUE',
    'CEDE',
    'CEDEROM',
    'CEINTURE',
    'CERCEAU',
    'CHAINE',
    'CHAISE',
    'CHAISES',
    'CHANSON',
    'CHAPEAU',
    'CHARGER',
    'CHAT',
    'CHAUD',
    'CHAUSSETTE',
    'CHAUSSON',
    'CHAUSSURE',
    'CHEMISE',
    'CHERCHER',
    'CHEVILLE',
    'CHIFFRE',
    'CHOISIR',
    'CHOSE',
    'CHUCHOTER',
    'CHUTE',
    'CIGARETTE',
    'CINQ',
    'CISEAUX',
    'CLASSE',
    'CLAVIER',
    'CLE',
    'CLOU',
    'COIN',
    'COL',
    'COLERE',
    'COLLANT',
    'COLLE',
    'COLLER',
    'COLORIAGE',
    'COLORIER',
    'COMMENCER',
    'COMPARER',
    'COMPTER',
    'CONDUIRE',
    'CONSTRUIRE',
    'CONTE',
    'CONTINUER',
    'CONTRAIRE',
    'CONTRE',
    'COPAIN',
    'COPIER',
    'COQUILLAGE',
    'COQUILLETTE',
    'COQUIN',
    'CORDE',
    'CORPS',
    'COTE',
    'COU',
    'COUCHE',
    'COUDE',
    'COUDRE',
    'COULEUR',
    'COULOIR',
    'COUPER',
    'COURIR',
    'COURONNE',
    'COURT',
    'CRAIE',
    'CRAVATE',
    'CROCHET',
    'CUBE',
    'CUILLERE',
    'CUISSE',
    'CULOTTE',
    'CURIEUX',
    'CUVETTE',
    'DAME',
    'DANGER',
    'DANS',
    'DANSER',
    'DE',
    'DEBORDER',
    'DEBOUT',
    'DECHIRER',
    'DECOLLER',
    'DECORER',
    'DECOUPAGE',
    'DECOUPER',
    'DEDANS',
    'DEFENDRE',
    'DEHORS',
    'DELTAPLANE',
    'DEMANDER',
    'DEMARRER',
    'DEMOLIR',
    'DEPASSER',
    'DERNIER',
    'DERRIERE',
    'DESCENDRE',
    'DESOBEIR',
    'DESSIN',
    'DESSINER',
    'DETRUIRE',
    'DEUX',
    'DEUXIEME',
    'DEVANT',
    'DICTIONNAIRE',
    'DIFFERENCE',
    'DIFFERENT',
    'DIFFICILE',
    'DIRE',
    'DIRECTEUR',
    'DIRECTRICE',
    'DISCUTER',
    'DISPARAITRE',
    'DISTRIBUER',
    'DIX',
    'DOIGT',
    'DOIGTS',
    'DOMINO',
    'DONNER',
    'DORMIR',
    'DOS',
    'DOSSIER',
    'DOUCHE',
    'DOUCHER',
    'DOUX',
    'DROIT',
    'DU',
    'DUR',
    'EAU',
    'ECARTER',
    'ECHANGER',
    'ECHARPE',
    'ECHASSES',
    'ECHELLE',
    'ECLABOUSSER',
    'ECLAIRER',
    'ECOLE',
    'ECOUTER',
    'ECRAN',
    'ECRASER',
    'ECRIRE',
    'ECRITURE',
    'EFFACER',
    'EFFORT',
    'ELASTIQUE',
    'ELECTRICITE',
    'ELEVE',
    'EMMENER',
    'EMPORTER',
    'ENCORE',
    'ENERVE',
    'ENFANT',
    'ENFILER',
    'ENFONCER',
    'ENGIN',
    'ENLEVER',
    'ENTENDRE',
    'ENTONNOIR',
    'ENTOURER',
    'ENTREE',
    'ENTRER',
    'ENVELOPPE',
    'ENVOYER',
    'EPAIS',
    'EPAULE',
    'EPEE',
    'EQUIPE',
    'ESCABEAU',
    'ESCALADER',
    'ESCALIER',
    'ESCARGOT',
    'ESCARPIN',
    'ESSUYER',
    'ETAGERE',
    'ETANG',
    'ETIQUETTE',
    'ETROIT',
    'ETUDE',
    'ETUDIER',
    'EXPLIQUER',
    'EXTERIEUR',
    'FABRIQUER',
    'FACILE',
    'FAIRE',
    'FATIGUE',
    'FAUTE',
    'FAUTEUIL',
    'FEE',
    'FENETRE',
    'FERMER',
    'FESSE',
    'FEU',
    'FEUILLE',
    'FEUTRE',
    'FICELLE',
    'FIL',
    'FILET',
    'FILLE',
    'FILM',
    'FINIR',
    'FLECHE',
    'FLEUR',
    'FLOTTER',
    'FOIS',
    'FONCE',
    'FOND',
    'FOOTBALL',
    'FORT',
    'FOUILLER',
    'FRAPPER',
    'FREIN',
    'FROID',
    'FUSEE',
    'FUSIL',
    'GAGNER',
    'GANT',
    'GARAGE',
    'GARÇON',
    'GARDER',
    'GARDIEN',
    'GARE',
    'GAUCHE',
    'GENER',
    'GENOU',
    'GENTIL',
    'GLISSER',
    'GOLF',
    'GOMME',
    'GONFLER',
    'GOUTER',
    'GOUTTES',
    'GRAND',
    'GRIMPER',
    'GRIS',
    'GRONDER',
    'GROS',
    'GROUPE',
    'GRUE',
    'GYMNASTIQUE',
    'HABIT',
    'HANCHE',
    'HANDICAPE',
    'HAUT',
    'HELICOPTERE',
    'HEXAGONE',
    'HISTOIRE',
    'HORLOGE',
    'HUIT',
    'HUMIDE',
    'IDEE',
    'ILE',
    'IMAGE',
    'IMITER',
    'IMMEUBLE',
    'IMMOBILE',
    'INONDER',
    'INSEPARABLE',
    'INSTRUMENT',
    'INTERESSANT',
    'INTERIEUR',
    'INTRUS',
    'JALOUX',
    'JAMBES',
    'JAUNE',
    'JEAN',
    'JEU',
    'JOLI',
    'JOUER',
    'JOUET',
    'JUPE',
    'LAC',
    'LACER',
    'LACET',
    'LAINE',
    'LAISSER',
    'LARGE',
    'LAVABO',
    'LAVER',
    'LECTURE',
    'LETTRE',
    'LIERRE',
    'LIGNE',
    'LINGE',
    'LIRE',
    'LISSE',
    'LISTE',
    'LIT',
    'LITRE',
    'LIVRE',
    'LOIN',
    'LONG',
    'LUMIERE',
    'LUNETTES',
    'MADAME',
    'MAGAZINE',
    'MAGICIEN',
    'MAGIE',
    'MAGNETOSCOPE',
    'MAILLOT',
    'MAIN',
    'MAINS',
    'MAISON',
    'MAITRE',
    'MAITRESSE',
    'MAL',
    'MALADROIT',
    'MANCHE',
    'MANQUER',
    'MANTEAU',
    'MARCHE',
    'MARIONNETTE',
    'MARTEAU',
    'MATELAS',
    'MATERNELLE',
    'MELANGER',
    'MEME',
    'MENSONGE',
    'MESURER',
    'METAL',
    'METRE',
    'METTRE',
    'MEUBLE',
    'MICRO',
    'MIEUX',
    'MILIEU',
    'MINE',
    'MODELE',
    'MOINS',
    'MONTAGNE',
    'MONTER',
    'MONTRER',
    'MORCEAU',
    'MOT',
    'MOTEUR',
    'MOTO',
    'MOUCHOIR',
    'MOUFLE',
    'MOUILLE',
    'MOUILLER',
    'MOULIN',
    'MOUSSE',
    'MOYEN',
    'MUET',
    'MULTICOLORE',
    'MUR',
    'MUSCLE',
    'MUSIQUE',
    'NAGER',
    'NENUPHAR',
    'NEUF',
    'NŒUD',
    'NOIR',
    'NOM',
    'NOMBRE',
    'NOUVEAU',
    'NU',
    'NUMERO',
    'OBEIR',
    'OBJET',
    'OBLIGER',
    'ONGLE',
    'ORCHESTRE',
    'ORDINATEUR',
    'ORDRE',
    'OURS',
    'OUTIL',
    'OUVRIR',
    'PAGE',
    'PAIRE',
    'PANNE',
    'PANTALON',
    'PAPIER',
    'PARACHUTE',
    'PARCOURS',
    'PAREIL',
    'PARKING',
    'PARLER',
    'PARTAGER',
    'PARTIR',
    'PAS',
    'PASSERELLE',
    'PATAUGER',
    'PEDALO',
    'PEINDRE',
    'PEINTURE',
    'PELUCHE',
    'PENTE',
    'PERCER',
    'PERDRE',
    'PERLE',
    'PERSONNE',
    'PETIT',
    'PEU',
    'PEUR',
    'PHOTO',
    'PIED',
    'PIEDS',
    'PILOTE',
    'PINCEAU',
    'PION',
    'PLACARD',
    'PLAFOND',
    'PLAGE',
    'PLANCHE',
    'PLÂTRE',
    'PLEUVOIR',
    'PLI',
    'PLIAGE',
    'PLIER',
    'PLONGEOIR',
    'PLONGER',
    'PLUIE',
    'PLUS',
    'PNEU',
    'POCHE',
    'POIGNET',
    'POING',
    'POINT',
    'POINTE',
    'POINTU',
    'POISSON',
    'POLI',
    'POMPIERS',
    'PONT',
    'PORTE',
    'PORTEMANTEAU',
    'PORTER',
    'POSER',
    'POSTER',
    'POT',
    'POUBELLE',
    'POUCE',
    'POUSSER',
    'POUVOIR',
    'PREMIER',
    'PRENDRE',
    'PRENOM',
    'PREPARER',
    'PRES',
    'PRESENT',
    'PRESQUE',
    'PRESSER',
    'PRETER',
    'PRINCE',
    'PRISES',
    'PRIVER',
    'PROMETTRE',
    'PROPRE',
    'PUNAISE',
    'PUNIR',
    'PUZZLE',
    'PYJAMA',
    'PYRAMIDE',
    'QUAI',
    'QUATRE',
    'QUESTION',
    'RACONTER',
    'RADIATEUR',
    'RADIO',
    'RAME',
    'RAMPE',
    'RAMPER',
    'RANGER',
    'RATER',
    'RAYURE',
    'RECEVOIR',
    'RECITER',
    'RECOMMENCER',
    'RECREATION',
    'RECULER',
    'REFUSER',
    'REGARDER',
    'REINE',
    'REMETTRE',
    'REMPLACER',
    'REMPLIR',
    'RENTREE',
    'RENTRER',
    'RENVERSER',
    'REPARER',
    'REPETER',
    'REPONDRE',
    'RESPIRER',
    'RESSEMBLER',
    'RESTER',
    'RETARD',
    'REUSSIR',
    'REVENIR',
    'RIDEAU',
    'ROBE',
    'ROBINET',
    'ROI',
    'ROND',
    'ROUE',
    'ROUGE',
    'ROULADE',
    'ROULER',
    'ROUX',
    'RUBAN',
    'RUGUEUX',
    'SAGE',
    'SALADIER',
    'SALE',
    'SALLE',
    'SAUT',
    'SAUTER',
    'SAVON',
    'SCIE',
    'SEAU',
    'SEC',
    'SECHER',
    'SEMELLE',
    'SENS',
    'SENTIR',
    'SEPARER',
    'SEPT',
    'SERIEUX',
    'SERPENT',
    'SERRE',
    'SERRER',
    'SERRURE',
    'SERVIETTE',
    'SERVIR',
    'SEUL',
    'SIEGE',
    'SIESTE',
    'SILENCE',
    'SIX',
    'SOL',
    'SOLDAT',
    'SOLIDE',
    'SOMMEIL',
    'SONNER',
    'SONNETTE',
    'SORCIERE',
    'SORTIE',
    'SORTIR',
    'SOUFFLER',
    'SOULEVER',
    'SOULIGNER',
    'SOUPLE',
    'SOURD',
    'SOURIRE',
    'SOUS',
    'SPAGHETTI',
    'SPORT',
    'STYLO',
    'SUIVANT',
    'SUIVRE',
    'SUR',
    'SURFEUR',
    'TABLE',
    'TABLEAU',
    'TABLIER',
    'TABOURET',
    'TACHE',
    'TAILLE',
    'TAILLER',
    'TALON',
    'TAMBOUR',
    'TAMPON',
    'TAPER',
    'TAPIS',
    'TARD',
    'TASSE',
    'TELECOMMANDE',
    'TELEPHONE',
    'TELEVISION',
    'TENDRE',
    'TENIR',
    'TENNIS',
    'TERMINER',
    'TETE',
    'TIRER',
    'TIROIR',
    'TISSU',
    'TITRE',
    'TOBOGGAN',
    'TOILETTE',
    'TOMBER',
    'TORDU',
    'TOT',
    'TOUCHER',
    'TOUR',
    'TOURNER',
    'TOURNEVIS',
    'TRAIN',
    'TRAIT',
    'TRAMPOLINE',
    'TRANQUILLE',
    'TRANSPARENT',
    'TRANSPIRER',
    'TRANSPORTER',
    'TRAVAIL',
    'TRAVAILLER',
    'TRAVERSER',
    'TREMPER',
    'TRICHER',
    'TRICOT',
    'TRIER',
    'TROIS',
    'TROISIEME',
    'TROMPETTE',
    'TROP',
    'TROUER',
    'TROUS',
    'TROUSSE',
    'TUNNEL',
    'UN',
    'UNIFORME',
    'USE',
    'VACHE',
    'VALISE',
    'VASE',
    'VEHICULE',
    'VENIR',
    'VENTRE',
    'VERRE',
    'VERS',
    'VERSER',
    'VERT',
    'VESTE',
    'VETEMENT',
    'VIDER',
    'VIRAGE',
    'VIS',
    'VITE',
    'VITESSE',
    'VITRE',
    'VOITURE',
    'VOIX',
    'VOLER',
    'VOULOIR',
    'VOYAGE',
    'WAGON',
    'XYLOPHONE',
    'ZERO',
    'ZIGZAG',
    'OLIVIA-BENSON',
    'JOHN-MUNCH',
    'DON-CRAGEN',
    'ELLIOT-STABLER',
    'MONIQUE-JEFFRIES',
    'ODAFIN-TUTUOLA',
    'ALEXANDRA-CABOT',
    'MELINDA-WARNER',
    'GEORGE-HUANG',
    'CASEY-NOVAK',
    'IAC',
    'KIM-GREYLEK',
    'AMANDA-ROLLINS',
    'KIM-ROLLINS',
    'NICK-AMARO',
    'RAFAEL-BARBA',
    'DOMINICK-CARISI-JR',
    'STONE',
    'ERIN-LINDSAY',
    'KATHY-STABLER',
    'STEVEN-HARRIS',
    'LUKE-BRESLIN',
    'GABRIELLE-VEGA',
    'SANDRA-ROBERTS',
    'NARUTO',
    'SAKURA',
    'SASUKE',
    'CHOJI',
    'INO',
    'SHIKAMARU',
    'HINATA',
    'KIBA',
    'SHINO',
    'NEJI',
    'ROCKLEE',
    'TENTEN',
    'KONOHAMARU',
    'MOEGI',
    'UDON',
    'HIRUZEN',
    'HOMURA',
    'DANZO',
    'KAGAMI',
    'TORIFU',
    'JIRAYA',
    'OROCHIMARU',
    'TSUNADE',
    'KAKASHI',
    'OBITO',
    'RIN',
    'AYAME',
    'ITACHI'
];

window.addEventListener('load', init);

function init() {
    console.log('ok');
}

function tabClavier() {
    let choix = [];
    // on commence a 65 car c est la qu est le A dans la table ascii et 90 correspond au z
    for (let index = 65; index <= 90; index++) {
        //String.fromCharCode cette indtruction permet de transformer le 
        //code ascii en charactere affichable
        // push permet de remplir le tableau
        choix.push(String.fromCharCode(index));
    }
    return choix;//renvoi un tableau remplis des lettres de l alphabet
};

function afficheClavier(choix) {
    test = [];
    for (let i = 0; i < choix.length; i++) {
        test[i] = '<button class="touche">' + choix[i] + '</button>';
    }
    return test.join('');//sinon les ',' s affichent
}


function choixMot() {
    let mot = dico[Math.floor(Math.random() * dico.length)];
    return mot;
}

function coderMot(mot) {
    tab = mot.split('');

    for (i = 1; i < tab.length - 1; i++) {
        if (tab[i] == '-') {
            tab[i] = '-';
        }
        else {
            tab[i] = '_';
        }

    }

    return tab.join('');// join permet de transformer l array en string
}

function afficherMot(motCoder) {
    afficheMot.innerHTML = '<h3>' + motCoder + '</h3>';
}

function testerLettre(lettre, mot) {
    res = mot.indexOf(lettre);
    if (res == -1) {
        return -1;
    }
    else {
        return 1;
    }
}

function creerPos(lettre, mot) {
    var tabPos = [];
    for (let i = 0; i < mot.length; i++) {
        if (lettre == mot[i]) {
            tabPos.push(i);
        }
    }
    return tabPos;
}

function ajouterLettre(mot, index, lettre) {


    mot = mot.substr(0, index) + lettre + mot.substr(index + 1);

    return mot;
}

function ajouterLesLettre(motCoder, mot, lettre) {

    var tabPos = creerPos(lettre, mot);
    console.log(tabPos);
    if (tabPos != null) {
        for (let i = 0; i < tabPos.length; i++) {

            let index = tabPos[i];
            motCoder = ajouterLettre(motCoder, index, lettre);
        }
    }

    return motCoder;
}

function dessinePendu(nbErreurs) {
    dessin.src = 'img/00' + nbErreurs + '.png';
}

function testerGagner(nbErreurs, motCoder) {
    if (nbErreurs == 8) // si nb erreur =8, partie perdue
    {
        return -1;
    }
    else if (motCoder.indexOf('_') == -1) // s'il y a un _ dans le tableau, la partie est en cours
    {
        return 1;
    }
    else {
        return 0;
    }
}

var afficheMot = document.querySelector('#motChoisi');
var clavier = document.querySelector('#clavier');
var temps = document.querySelector('#temp');
var nbErreurs = 0;
var dessin = document.querySelector('#dessin');
var reload = document.querySelector('#reload');

var mot = choixMot();
var motCoder = coderMot(mot);
console.log(motCoder);
var boutons = tabClavier();
clavier.innerHTML = afficheClavier(boutons);

console.log(mot);

afficherMot(motCoder);

clavier.addEventListener('click', function (e) {
    var lettreChoisi = e.target;
    var lettre = lettreChoisi.textContent;
    lettreChoisi.classList.add('desactive');
    var test = testerLettre(lettre, mot, 0);
    if (test == -1) {
        nbErreurs++;
        dessinePendu(nbErreurs);

    }
    else {
        motCoder = ajouterLesLettre(motCoder, mot, lettre);
    }

    afficherMot(motCoder);
    console.log('err: ' + nbErreurs);
    var verif = testerGagner(nbErreurs, motCoder);
    var fin = document.querySelector('.fin');
    var finDujeu = document.querySelector('#finDeJeu');
    if (verif == 1) {
        fin.style.display = "flex";
        finDujeu.innerHTML = 'vous avez gagner';
    }
    else if (verif == -1) {
        fin.style.display = "flex";
        dessin.style.backgroundColor = "red";
        finDujeu.innerHTML = 'vous avez perdu';
    }

});

reload.addEventListener("click",function(){
    document.location.reload();
})












